# Generated by Django 4.1.2 on 2022-11-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='minicursos',
            field=models.IntegerField(),
        ),
    ]
